<?php $_controller = (!empty($this->request->data['MenuItem']['controller']))? $this->request->data['MenuItem']['controller']: ''; ?>
<?php echo $this->Form->input('controller', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Select Link'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'options' => $links, 'selected' => $_controller, 'empty' => ''));?>
<?php echo $this->Form->input('action', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Select Page'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'options' => $slugs, 'selected' => $_slug, 'empty' => '', 'type' => 'select'));?>
<?php echo $this->Form->input('url', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Url'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>'));?>

<?php echo $this->Form->input('page_title', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Page Title'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>')); ?>
<?php echo $this->Form->input('show_title', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Show Title'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'empty' => '', 'options' => array(0 => 'No', 1 => 'Yes'))); ?>
<?php echo $this->Form->input('page_kw', array('div' => 'form-group', 'label' => array('text' => __('Page Keywords'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'type' => 'textarea', 'class' => 'form-control', 'rows' => 10));?>
<?php echo $this->Form->input('page_meta', array('div' => 'form-group', 'label' => array('text' => __('Page Metadata'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'type' => 'textarea', 'class' => 'form-control', 'rows' => 10));?>
